import Head from "next/head";
import Image from "next/image";
import svg from "../public/images/svg.png";
import svg1 from "../public/images/svg1.png";
import svg2 from "../public/images/svg2.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main>
        <div className="main">
          <div className="container header">
            <div className="container-fluid">
              <div className="brand">
                <h1>Content...</h1>
              </div>
              <div>
                <a className="route" href="https://github.com/">
                  Home
                </a>
                <a className="route" href="https://github.com/">
                  Case Studies
                </a>
                <a className="route" href="https://github.com/">
                  Contact
                </a>
              </div>
            </div>
          </div>
          <div className="container landing">
            <div className="container-fluid">
              <div className="col-4">
                <div className="landing-bg-top"></div>
                <div className="landing-bg-bottom"></div>
                <div className="landing-bg-left"></div>
                <h1 className="slogan">Another landing page for startups</h1>
                <p>
                  Lorem Ipsum is simply dummy text of the printing and
                  typesetting industry.
                </p>
                <button className="landing-button">Get Started</button>
              </div>
              <div className="landing-img">
                <div>
                  <div className="landing-img-item mb-7">item</div>
                </div>
                <div>
                  <div className="landing-img-item">item</div>
                  <div className="landing-img-item img-item-height">item</div>
                </div>
                <div>
                  <div className="landing-img-item">item</div>
                  <div className="landing-img-item">item</div>
                  <div className="landing-img-item">item</div>
                </div>
              </div>
            </div>
          </div>

          <div className="discount">
            <div className="discount-item">
              <div>
                <Image
                  src={svg}
                  alt="Picture of the author"
                  width={100}
                  height={100}
                />
              </div>
              <h3 className="discount-title">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit
              </h3>
              <p>
                Sed ut perspiciatis unde omnis iste natus error sit voluptatem
                accusantium doloremque laudantium, totam rem aperiam.
              </p>
            </div>
            <div className="discount-item">
              <div>
                <Image
                  src={svg1}
                  alt="Picture of the author"
                  width={100}
                  height={100}
                />
              </div>
              <h3 className="discount-title">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit
              </h3>
              <p>
                Sed ut perspiciatis unde omnis iste natus error sit voluptatem
                accusantium doloremque laudantium, totam rem aperiam.
              </p>
            </div>
            <div className="discount-item">
              <div>
                <Image
                  src={svg2}
                  alt="Picture of the author"
                  width={100}
                  height={100}
                />
              </div>
              <h3 className="discount-title">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit
              </h3>
              <p>
                Sed ut perspiciatis unde omnis iste natus error sit voluptatem
                accusantium doloremque laudantium, totam rem aperiam.
              </p>
            </div>
          </div>
          <div className="exp">
            <div className="exp-left">
              <div className="landing-img-item">item</div>
              <div className="landing-img-item mt-5">item</div>
            </div>
            <div className="exp-right">
              <h2 className="exp-title">
                Duis aute irure dolor in reprehenderit in voluptate velit esse
                cillum dolore
              </h2>
              <p className="exp-desc">
                Sed ut perspiciatis unde omnis iste natus error sit voluptatem
                accusantium doloremque laudantium, totam rem aperiam, eaque ipsa
                quae ab illo inventore veritatis et quasi architecto beatae
                vitae dicta sunt explicabo.
              </p>
            </div>
          </div>
          <div className="exp-s">
            <div className="exp-s-left">
              <h2 className="exp-title">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit
              </h2>
              <p className="exp-desc exp-s-desc">
                Sed ut perspiciatis unde omnis iste natus error sit voluptatem
                accusantium doloremque laudantium, totam rem aperiam, eaque ipsa
                quae ab illo inventore veritatis et quasi architecto beatae
                vitae dicta sunt explicabo.
              </p>
            </div>
            <div className="exp-s-right">
              <div className="landing-img-item">item</div>
              <div className="landing-img-item">item</div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
